#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


set -o xtrace

#stop services on controller-node
service vsm-api stop
service vsm-conductor stop
service vsm-scheduler stop

#get agent node hostnames
PWD=`cat /etc/vsmdeploy/deployrc | grep ROOT | awk -F "=" '{print $2}'`
nodes=`mysql -uroot -p${PWD} -e "use vsm;select host from init_nodes;"`

agent_nodes=${nodes[@]:4}

#clean databse vsm
mysql -uroot -p`cat /etc/vsmdeploy/deployrc | grep ROOT | awk -F "=" '{print $2}'` -e "drop database if exists vsm;create database vsm;"
vsm-manage db sync

#start services on controller-node
service vsm-api start
service vsm-conductor start
service vsm-scheduler start

#clean data in agent-nodes
for i in $agent_nodes
do
        ssh $i "__clean-data"
done

#replace-str agent-token and restart
token=`agent-token`
for i in $agent_nodes
do
        ssh $i "replace-str $token;service vsm-agent restart;service vsm-physical restart;"

done

set +o xtrace