#!/usr/bin/expect -f

#penssl genrsa -des3 -out server.key 1024
#Enter pass phrase for server.key:
#Verifying - Enter pass phrase for server.key:
spawn openssl genrsa -des3 -out server.key 1024

expect "Enter pass phrase for server.key:"
send "%PASSWORD%\r"

expect "Verifying - Enter pass phrase for server.key:"
send "%PASSWORD%\r"

expect eof
