#!/bin/sh
#
# vsm-physical  VSM Storage DB Service
#
# chkconfig:   - 98 02
# description: VSM Storage DB Service works on MySQL.
### END INIT INFO

. /lib/lsb/init-functions
sed -i 's,do_cmd.* 30 $BINDIR.*,do_cmd "timeout 30 $BINDIR/ceph -c $conf --name=osd.$id --keyring=$osd_keyring osd crush create-or-move -- $id ${osd_weight:-${defaultweight:-1}} $osd_location ||:",g' /etc/init.d/ceph;

NAME=vsm-physical
DAEMON=/usr/bin/vsm-physical
CONFIGFILE=/etc/vsm/vsm.conf
PIDFILE=/var/run/vsm-physical.pid
LOGFILE=/var/log/vsm/vsm-physical.log
DAEMON_OPTS="--config-file $CONFIGFILE --log-file $LOGFILE"

test -x $DAEMON || exit 5

[ -e /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME

LOCKFILE=/var/lock/vsm-physical

lock_vsmphysical() {
	if [ -x /usr/bin/lockfile-create ]; then
		lockfile-create $LOCKFILE
		lockfile-touch $LOCKFILE &
		LOCKTOUCHPID="$!"
	fi
}

unlock_vsmphysical() {
	if [ -x /usr/bin/lockfile-create ] ; then
		kill $LOCKTOUCHPID
		lockfile-remove $LOCKFILE
	fi
}

RUNASUSER=vsm

case $1 in
	start)
		log_daemon_msg "Starting VSM server" "vsm-physical"
		lock_vsmphysical
  		start-stop-daemon --start --quiet --oknodo --background --pidfile $PIDFILE --startas $DAEMON -- $DAEMON_OPTS
  		PID=`ps -ef|grep vsm-physical|awk -F ' ' '{ if($3==1) print $2 }'`
  		echo $PID > $PIDFILE

		status=$?
		unlock_vsmphysical
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping VSM server" "vsm-physical"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -rf $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "VSM server vsm-physical"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
