#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


function glance_prepare() {
    _del_pool ${AUTH_GLANCE_POOL}
    _create_pool ${AUTH_GLANCE_POOL}
    _del_user ${AUTH_GLANCE_USER}
}

function create_glance() {
    local file=/tmp/glance.keyring
    rm -rf $file

    glance_prepare

    ceph auth get-or-create ${AUTH_GLANCE_USER} \
        mon 'allow r' \
        osd "allow class-read object_prefix rbd_children, allow rwx pool=${AUTH_GLANCE_POOL}"

    ceph auth get-or-create ${AUTH_GLANCE_USER} -o $file

    mkdir -p $TOPDIR/files/glance/
    cp -rf /etc/ceph/ceph.conf $TOPDIR/files/glance/
    sed -i "s,keyring = /etc/ceph/keyring.admin,,g" $TOPDIR/files/glance/ceph.conf
    mv $file $TOPDIR/files/glance/

cat <<"EOF">>$TOPDIR/files/glance/ceph.conf
[%AUTH_GLANCE_USER%]
keyring=/etc/glance/glance.keyring
EOF

sed -i "s,%AUTH_GLANCE_USER%,$AUTH_GLANCE_USER,g" $TOPDIR/files/glance/ceph.conf

}
