#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

set -e
set -o xtrace

TOPDIR=$(cd $(dirname "$0") && pwd)
source $TOPDIR/localrc
source $TOPDIR/server/ceph

#-----------------------------------
# Pre-checking
#-----------------------------------

source $TOPDIR/lib/package

#-----------------------------------
# Glance
#-----------------------------------

source $TOPDIR/server/glance
create_glance

#-----------------------------------
# Cinder
#-----------------------------------

source $TOPDIR/server/cinder-main
create_cinder

#-----------------------------------
# Nova Must done after cinder
#-----------------------------------

source $TOPDIR/server/nova
create_nova

set +o xtrace
