#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

function setup_nova() {
    source $TOPDIR/server/tarfile

    AUTH_CINDER_UUID=$3
    AUTH_CINDER_USER=client.${AUTH_CINDER_UUID}
    AUTH_CINDER_POOL=$pool_name

    gen_tar_file $2 $4 $5 $TOPDIR/lib/config-nova
}