#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

function setup_cinder() {
    local pool_iter=0

    source $TOPDIR/server/ceph
    source $TOPDIR/lib/package
    source $TOPDIR/server/cinder
    source $TOPDIR/server/tarfile

    AUTH_CINDER_UUID=$3
    AUTH_CINDER_USER=client.${AUTH_CINDER_UUID}
    AUTH_CINDER_POOL=$pool_name

    #-----------------------------------
    # Collect all the pools.
    #-----------------------------------

    BACKEND_LIST=""
    for n in $@; do
        if [[ $pool_iter -lt 5 ]]; then
            let ++pool_iter
            continue
        fi
        let ++pool_iter

        pool_name=${n%,*}
        type_name=${n#*,}

        if [[ ${#BACKEND_LIST} -gt 0 ]]; then
            str=${BACKEND_LIST}","${pool_name}
            BACKEND_LIST=$str
        else
            BACKEND_LIST=$pool_name
        fi

        if [[ ${#TYPE_LIST} -gt 0 ]]; then
            str=${TYPE_LIST}","${type_name}
            TYPE_LIST=$str
        else
            TYPE_LIST=${type_name}
        fi
    done

    echo $BACKEND_LIST
    echo $TYPE_LIST
    create_cinder_auth

    gen_tar_file $2 $4 $5 $TOPDIR/lib/config-cinder
}
