#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


function is_service_running() {
    local file=`mktemp`
    service $1 status 1>$file 2>$file
    sleep 1
    cnt1=`cat $file | grep "is running" | wc -l`
    cnt2=`cat $file | grep "start/running" | wc -l`
    cnt3=`cat $file | grep "active (running)" | wc -l`
    let cnt=$cnt1+$cnt2+$cnt3
    if [[ $cnt -gt 0 ]]; then
        echo 1
    else
        echo 0
    fi
}
