#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


set -e

TOPDIR=$(cd "$(dirname "$0")" && pwd)

rm -rf $TOPDIR/vsmrepo.tar.gz
rm -rf $TOPDIR/vsmrepo
cd $TOPDIR
mkdir -p $TOPDIR/vsmrepo

set -o xtrace
TEMP=`mktemp`;
rm -rfv $TEMP >/dev/null;
mkdir -p $TEMP;
echo '%debug_package %{nil}' >> ~/.debmacros
#---------------------------------------------
# Load Function
#---------------------------------------------

SOURCE_DIR=source
VSM_DIR=vsm
VSMCLIENT_DIR=python-vsmclient
VSMDASHBOARD_DIR=vsm-dashboard
VSM_DEPLOY_DIR=vsm-deploy

source  $TOPDIR/.lib/setiptables
for n in `ls $TOPDIR/.lib/ | grep -v iptables`; do
    source $TOPDIR/.lib/$n
done

find $TOPDIR -name "*.pyc" | xargs -i rm -rf {}
find $TOPDIR -name "*.pyo" | xargs -i rm -rf {}

PACKAGE_NAMES=$1
if [[ $PACKAGE_NAMES != "" ]]
then
    PACKAGE_NAME_LIST=${PACKAGE_NAMES//,/ }
    for package_name in $PACKAGE_NAME_LIST
    do
        if [[ $package_name == "vsm" ]]
        then
            build_vsm_deb
        elif [[ $package_name == "python-vsmclient" ]]
        then
            build_vsmclient_deb
        elif [[ $package_name == "vsm-dashboard" ]]
        then
            build_vsm_dashboard_deb
        elif [[ $package_name == "vsm-deploy" ]]
        then
            build_vsmdeploy_deb
        else
            echo "vsm project does not include $package_name package"
        fi
    done
else
    build_vsm_deb
    build_vsmclient_deb
    build_vsm_dashboard_deb
    build_vsmdeploy_deb
fi

#---------------------------------------------
# Update vsmrepo
#---------------------------------------------

is_dpkg_dev=`dpkg -s dpkg-dev|grep "install ok installed"|wc -l`
if [[ $is_dpkg_dev -eq 0 ]]; then
    sudo apt-get install dpkg-dev
fi
dpkg-scanpackages vsmrepo | gzip > vsmrepo/Packages.gz

rm -rf $TEMP

set +o xtrace
