#!/bin/bash

# Copyright 2014 Intel Corporation, All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the"License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


function update_info() {
    local info=$1
    echo "-------------------------------"
    echo $VSM_API_TOKEN $VSM_API_URL $info
    echo "-------------------------------"
}

function exe() {
    local error_info=`$@ | grep ERROR`
    local cnt=`echo $error_info | wc -l`
    if [[ $cnt -gt 0 ]]; then
        update_info $error_info
    fi
}
