#!/bin/bash

debconf-set-selections <<< 'maria-db-server mysql-server/root_password password root'
debconf-set-selections <<< 'maria-db-server mysql-server/root_password_again password root'

apt-get install -y ceph apache2 libapache2-mod-wsgi librbd* mariadb-server memcached ntp openssh-server openssl keystone rabbitmq-server rbd-fuse expect

apt-get install -y ceph apache2 libapache2-mod-wsgi librbd* mariadb-server memcached ntp openssh-server openssl keystone rabbitmq-server rbd-fuse expect